import DashboardPage from "./DashboardPage";
import LoginPage from "./LoginPage";
import RegisterPage from "./RegisterPage";
import NotFound from "./NotFound";
import HomePage from "./HomePage";
import PemasukanPage from "./PemasukanPage";
import UploadPage from "./UploadPage";
import PengeluaranPage from "./PengeluaranPage";
import TabunganPage from "./TabunganPage";
import CatatTabunganPage from "./CatatTabunganPage";
import BuatTabunganPage from "./BuatTabunganPage";
import EditTabunganPage from "./EditTabunganPage";
import ProfilePage from "./ProfilePage";
import LupaKataSandiPage from "./LupaKataSandiPage";
import KonfirmasiPage from "./KonfirmasiPage";
import AturUlangKataSandiPage from "./AturUlangKataSandiPage";
import PrivacyPolicyPage from "./PrivacyPolicyPage";
import TermsOfServicePage from "./TermsOfServicePage";

export { DashboardPage, LoginPage, RegisterPage, NotFound, HomePage, PemasukanPage, UploadPage, PengeluaranPage, TabunganPage, CatatTabunganPage, BuatTabunganPage, EditTabunganPage, ProfilePage, LupaKataSandiPage, KonfirmasiPage, AturUlangKataSandiPage, PrivacyPolicyPage, TermsOfServicePage };